apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: playground
  name: pod-operator
rules:
- apiGroups: [""] # "" indicates the core API group
  resources: ["pods", "pods/log"]
  verbs: ["get", "watch", "list", "create"]
- apiGroups: ["batch"] # "" indicates the core API group
  resources: ["jobs"]
  verbs: ["get", "watch", "list", "create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: pod-operator
  namespace: playground
subjects:
- kind: User
  name: developer
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: pod-operator
  apiGroup: rbac.authorization.k8s.io

